# Generated by Django 2.1.1 on 2018-09-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_kind', models.CharField(choices=[('A', 'Cédula de ciudadanía'), ('B', 'Cédula de extrangería'), ('C', 'Nit')], default='A', max_length=1)),
                ('doc', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=20)),
                ('first_lastname', models.CharField(max_length=20)),
                ('second_lastname', models.CharField(max_length=20)),
                ('cellphone_number', models.CharField(max_length=20)),
                ('interested_sports', models.ManyToManyField(to='sports.Sport')),
            ],
        ),
    ]
